const crypto=require('crypto');
const json=(status,body)=>({statusCode:status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:JSON.stringify(body)});
const hash=p=>crypto.scryptSync(String(p),process.env.PASSWORD_SALT||process.env.SESSION_SECRET,64).toString('hex');
const token=payload=>Buffer.from(JSON.stringify(payload)).toString('base64url')+'.'+crypto.createHmac('sha256',process.env.SESSION_SECRET).update(Buffer.from(JSON.stringify(payload)).toString('base64url')).digest('base64url');
const readToken=e=>{const raw=(e.headers.authorization||'').replace('Bearer ','');const [p,s]=raw.split('.');if(!p||!s||s!==crypto.createHmac('sha256',process.env.SESSION_SECRET).update(p).digest('base64url'))throw Error('Please sign in again.');const data=JSON.parse(Buffer.from(p,'base64url'));if(data.exp<Date.now())throw Error('Your session has expired.');return data};
const db=async(path,options={})=>{const r=await fetch(process.env.SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});if(!r.ok)throw Error('Database request failed.');return r.status===204?[]:r.json()};
const levels={Depression:[[9,'Normal'],[13,'Mild'],[20,'Moderate'],[27,'Severe'],[99,'Extremely severe']],Anxiety:[[7,'Normal'],[9,'Mild'],[14,'Moderate'],[19,'Severe'],[99,'Extremely severe']],Stress:[[14,'Normal'],[18,'Mild'],[25,'Moderate'],[33,'Severe'],[99,'Extremely severe']]};
const groups={Depression:[2,4,9,12,15,16,20],Anxiety:[1,3,6,8,14,18,19],Stress:[0,5,7,10,11,13,17]};
async function sendEmail(report,client){if(!process.env.RESEND_API_KEY)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[process.env.OWNER_EMAIL],subject:`DASS-21 ${report.type.toUpperCase()} report — ${client.name}`,html:`<h2>DASS-21 ${report.type} report</h2><p><b>Client:</b> ${client.name} (${client.email})</p><p><b>Depression:</b> ${report.scores.Depression} (${report.severity.Depression})<br><b>Anxiety:</b> ${report.scores.Anxiety} (${report.severity.Anxiety})<br><b>Stress:</b> ${report.scores.Stress} (${report.severity.Stress})</p>`})})}
exports.handler=async event=>{try{if(event.httpMethod==='OPTIONS')return json(200,{});const path=event.queryStringParameters?.route||'/';const body=event.body?JSON.parse(event.body):{};
if(path==='/login'){const rows=await db(`clients?username=eq.${encodeURIComponent(body.username)}&select=*`);const c=rows[0];if(!c||c.password_hash!==hash(body.password))return json(401,{error:'Incorrect username or password.'});const reports=await db(`reports?client_id=eq.${c.id}&select=type,scores,severity,created_at&order=created_at.desc`);const tests=Object.fromEntries(reports.map(r=>[r.type,{...r,createdAt:r.created_at}]));return json(200,{token:token({id:c.id,exp:Date.now()+28800000}),name:c.name,tests})}
if(path==='/admin/login'){if(body.email!==process.env.OWNER_EMAIL||body.password!==process.env.ADMIN_PASSWORD)return json(401,{error:'Incorrect administrator credentials.'});return json(200,{token:token({admin:true,exp:Date.now()+28800000})})}
const auth=readToken(event);
if(path==='/submit'){if(auth.admin)return json(403,{error:'Client access required.'});if(!['pre','mid','post'].includes(body.type)||!Array.isArray(body.answers)||body.answers.length!==21||body.answers.some(x=>!Number.isInteger(x)||x<0||x>3))return json(400,{error:'Invalid assessment answers.'});const old=await db(`reports?client_id=eq.${auth.id}&type=eq.${body.type}&select=id`);if(old.length)return json(409,{error:'This assessment has already been completed.'});const prior=await db(`reports?client_id=eq.${auth.id}&select=type`);if((body.type==='mid'||body.type==='post')&&!prior.some(r=>r.type==='pre'))return json(403,{error:'Complete the pre assessment first.'});const scores=Object.fromEntries(Object.entries(groups).map(([n,ids])=>[n,ids.reduce((sum,i)=>sum+body.answers[i],0)*2]));const severity=Object.fromEntries(Object.entries(scores).map(([n,s])=>[n,levels[n].find(x=>s<=x[0])[1]]));const created=(await db('reports',{method:'POST',body:JSON.stringify({client_id:auth.id,type:body.type,answers:body.answers,scores,severity})}))[0];const client=(await db(`clients?id=eq.${auth.id}&select=name,email`))[0];await sendEmail(created,client);const all=await db(`reports?client_id=eq.${auth.id}&select=type,scores,severity,created_at`);return json(200,{report:{...created,createdAt:created.created_at},tests:Object.fromEntries(all.map(r=>[r.type,{...r,createdAt:r.created_at}]))})}
if(!auth.admin)return json(403,{error:'Administrator access required.'});if(path==='/admin/clients'){if(!body.name||!body.email||!body.username||String(body.password).length<8)return json(400,{error:'Please complete every client field; password must have 8 characters.'});await db('clients',{method:'POST',body:JSON.stringify({name:body.name,email:body.email,username:body.username,password_hash:hash(body.password)})});return json(201,{ok:true})}if(path==='/admin/reports'){const reports=await db('reports?select=type,scores,severity,created_at,clients(name,email)&order=created_at.desc');return json(200,{reports:reports.map(r=>({...r,clientName:r.clients.name,createdAt:r.created_at}))})}return json(404,{error:'Not found.'})}catch(e){return json(500,{error:e.message||'Server error.'})}};
